apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: suraj7340/text-app:001
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # Adding health checks (customize the path and port as needed)
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service  # Updated name for clarity
spec:
  selector:
    app: myapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: LoadBalancer